spring:
  config:
    activate:
      on-profile: local,dev,prod
  application:
    name: batch
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    db:
      enabled: false